server:
  port: 7002
spring:
  application:
    name: vast-gateway


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

zuul:
  ignored-services: "*"
  sensitive-headers:
  prefix: /api #为zuul设置一个公共的前缀
  routes:
    system:
      path: /sys/**
      serviceId: vast-system
    auth:
      path: /auth/**
      serviceId: vast-auth
