eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: vast-geteway
zuul:
  prefix: /api #为zuul设置一个公共的前缀
  routes:
    auth:
      path: /auth/**
      serviceId: vast-auth
    system:
      path: /system/**
      serviceId: vast-system
