server:
  port: 7002
spring:
  application:
    name: vast-gateway
  profiles:
    include: common

zuul:
  ignored-services: "*"
  sensitive-headers:
  prefix: /api #为zuul设置一个公共的前缀
  routes:
    system:
      path: /sys/**
      serviceId: vast-system
    auth:
      path: /auth/**
      serviceId: vast-auth
