vast:
  security:
    token:
      expiration-time: 7200 # 秒
      refresh-exp-time: 604800 # 秒
      issuer: http://www.vast.com
      signing-key: fa647256f7484f6593cfaa92e097061e
    ignore:
      urls: #配置白名单路径
        - "/api/auth/oauth/token"
  minio:
    enable: false
    bucket-name: vast
    access-key: minioadmin
    secret-key: minioadmin
    endpoint: http://127.0.0.1:9000
swagger:
  enable: true
spring:
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  data:
    cassandra:
      keyspace-name: jinpeng #键空间名称
      contact-points: 127.0.0.1 #服务器IP地址
      port: 9042 #默认端口
      session-name: Test Cluster #默认的集群名字
      local-datacenter: datacenter1 #默认的数据中心
  #      username: cassandra
  #      password: cassandra
  banner:
    location: classpath:banner.txt
  activiti:
    check-process-definitions: false
    database-schema-update: true
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vast_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=15000
    useGlobalDataSourceStat: true
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/vast_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/gps?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
  mongodb:
    database: user
    host: 127.0.0.1
    port: 27017
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
http:
  proxy:
    enabled: false
    host: 127.0.0.1
    port: 80

