server:
  port: 7003
spring:
  application:
    name: vast-auth


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
